[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fpdf>=1.7.2",
    "openai>=1.77.0",
    "pypdf2>=3.0.1",
    "streamlit>=1.45.0",
]
